/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Excepciones.PokerExcepciones;
import controlador.ControladorLogin;
import controlador.VistaLogin;
import controlador.VistaLoginParticipante;
import iu.MesaJuego;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Fachada;
import modelo.Juego;
import modelo.Jugador;
import modelo.Participante;
import modelo.SistemaJuegos;
import modelo.Usuario;


public class LoginJugador extends javax.swing.JFrame implements VistaLoginParticipante{ 
 private  ControladorLogin controlador;
    /**
     * Creates new form LoginJugador
     */
    public LoginJugador() {
        initComponents();
        controlador = new ControladorLogin(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_pass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(txt_name);
        txt_name.setBounds(120, 40, 150, 27);

        jLabel1.setText("Login:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 40, 42, 17);

        jLabel2.setText("Password:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 90, 60, 17);

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 130, 69, 29);
        getContentPane().add(txt_pass);
        txt_pass.setBounds(120, 90, 150, 27);

        setBounds(0, 0, 416, 207);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     try {
         login();
     } catch (PokerExcepciones ex) {
         Logger.getLogger(LoginJugador.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_jButton1ActionPerformed

    @Override
    public void errorLoginIncorrecto(String msg) {
        
        JOptionPane.showMessageDialog(this, msg);
    
    }

   

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txt_name;
    private javax.swing.JPasswordField txt_pass;
    // End of variables declaration//GEN-END:variables

     @Override
    public void ingresar(Participante u)  throws PokerExcepciones{
        
      Juego juego = Fachada.getInstancia().getSiguienteJuego();
       Fachada.getInstancia().agregarJugadorSiguienteJuego(u);
       
         /* Esto lo cambiamos manana, preguntar al docente si esta bien ponerlo en el constructor el juego*/
         new MesaJuego(u, juego).setVisible(true);
        dispose();
        
    }
    
    
    private void login() throws PokerExcepciones {
         String pwd = new String(txt_pass.getPassword());
        controlador.loginJugador(txt_name.getText(), pwd);
    }

  
}
