/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Excepciones.PokerExcepciones;
import iu.MenuAdministrador;
import controlador.ControladorLogin;
import controlador.VistaLogin;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Administrador;
import modelo.Usuario;

/**
 *
 * @author alex
 */
public class LoginAdmin extends javax.swing.JFrame implements VistaLogin{

    private ControladorLogin controlador;
    /**
     * Creates new form LoginAdmin
     */
    public LoginAdmin() {
        initComponents();
        controlador = new ControladorLogin(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Login :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 30, 60, 20);

        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });
        getContentPane().add(txtLogin);
        txtLogin.setBounds(120, 30, 200, 20);

        jLabel2.setText("Password : ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 80, 80, 14);
        getContentPane().add(txtPassword);
        txtPassword.setBounds(120, 80, 200, 20);

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(292, 120, 80, 23);

        setBounds(0, 0, 410, 196);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
        login();
        
        } catch (PokerExcepciones ex) {
         Logger.getLogger(LoginAdmin.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables

    @Override
    public void errorLoginIncorrecto(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }

    @Override
    public void ingresar(Usuario u) {
        dispose();
        try{
            new MenuAdministrador((Administrador)u).setVisible(true);
        } catch (IOException ex) {
         Logger.getLogger(LoginAdmin.class.getName()).log(Level.SEVERE, null, ex);
     }
    }

    private void login()throws PokerExcepciones  {
        String pwd = new String(txtPassword.getPassword());
        controlador.loginAdmin(txtLogin.getText(), pwd);
    }
}
